'''You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
Example 1:input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
'''


'''firstly converted string s to list then mach each element of t in s_list if these character are mached then remove otherwise return'''
def difference(s,t):
    s_list = list(s)
    for ch in t:
        if ch in s_list:
            s_list.remove(ch)
        else:
            return ch
            
s = "abcd"
t = "abcde"
print(difference(s,t))